events {
    worker_connections 1024;
}

http {
    # Mendefinisikan zona memori untuk menyimpan status permintaan
    # Berdasarkan alamat IP klien ($binary_remote_addr)
    # Nama zona: threads_limit, Ukuran: 10m
    # Rate: 90 permintaan per menit (90r/m)
    limit_req_zone $binary_remote_addr zone=threads_limit:10m rate=90r/m;

    server {
        listen 80;
        server_name localhost;

        # Limit access 90 req/min untuk resource /threads dan sub-path di dalamnya
        location /threads {
            limit_req zone=threads_limit burst=20 nodelay;

            proxy_pass http://localhost:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Resource lainnya diteruskan normal tanpa limit khusus
        location / {
            proxy_pass http://localhost:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}